"""
Django settings for lab1 project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'SECRET_KEY', 
    default='django-insecure-*pgkn(28-w!tvt_6rx!8tf73ht#r9k=qod^#x90u6(8fjmd9)2'
)


# SECURITY WARNING: don't run with debug turned on in production!
# Render дээр байгаа эсэхээс хамааруулан автоматаар False болгоно
DEBUG = 'RENDER' not in os.environ


# Render-д зориулсан ALLOWED_HOSTS тохиргоо
ALLOWED_HOSTS = []

# Render өөрөө RENDER_EXTERNAL_HOSTNAME env var өгдөг тул автоматаар нэмнэ
RENDER_EXTERNAL_HOSTNAME = os.environ.get('RENDER_EXTERNAL_HOSTNAME')
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)

# Туршихад түр зуур '*' тавьж болно (дараа нь устгаарай!)
# ALLOWED_HOSTS = ['*']   # ← Энд түр зуур асааж туршиж болно


# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'app_one',
    'app_two',
]


# Whitenoise – static файлуудыг зөв serve хийхэд хэрэгтэй (Render дээр чухал)
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',          # ← Энд нэмэгдсэн
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


ROOT_URLCONF = 'lab1.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'lab1.wsgi.application'


# Database – Render дээр PostgreSQL ашиглахыг зөвлөдөг (одоогоор SQLite үлдээсэн)
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Хэрэв Render-ийн PostgreSQL-г ашиглах бол доорхыг ашигла (dj-database-url суулгах хэрэгтэй)
# import dj_database_url
# DATABASES = {
#     'default': dj_database_url.config(default=os.environ.get('DATABASE_URL'))
# }


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'                      # ← collectstatic энд цуглуулна

# Whitenoise-д зориулсан тохиргоо (compressed файлууд)
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
